services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        ports:
            - 8080:80
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=project5
            - DB_USERNAME=root
            - DB_PASSWORD=
        depends_on:
            - db

    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=project5
            - MYSQL_USER=root
            - MYSQL_PASSWORD=

volumes:
    db_data:
