name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pdo_mysql
        tools: composer:v2
   
    - name: Install Dependencies
      run: composer install

    # - name: Test Application
    #   run: ./vendor/bin/phpunit
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.danielshahzada }}
        password: ${{ secrets.dckr_pat_3V63_4l6FfWNGYG60ape-lI-7As }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: danielshahzada/project5:latest
